export default function Home(){return <div className="app"><Sidebar/><main className="main"><Topbar/><div className="content"><div className="page-title"><div><h1>Dashboard</h1><p className="muted">Prezentare generală proiect și progres actual</p></div><div className="actions"><button className="btn">+ Adaugă</button><button className="btn light">Export raport</button></div></div><Dashboard/></div></main></div>}
function Sidebar(){const items=['Planuri','Gantt','Calendar','Task Manager','Site Diary','Photo Station','AI Vision','Materials','Procurement','Cost Control','Technical Library','Reports','Share View','Settings'];return <aside className="sidebar"><div className="brand"><div className="shield">⌂</div><div><div className="brand-title">PM OMIFA</div><div className="brand-sub">v2.2 Preview</div></div></div><button className="navbtn active">⌂ Dashboard</button><div className="section-label">PROJECT</div>{items.map(i=><button className="navbtn" key={i}>{i}</button>)}<div className="project-mini"><div className="project-row"><div className="thumb"></div><div><b>Lemon Office Fit-Out</b><div className="brand-sub">București, România</div></div></div></div></aside>}
function Topbar(){return <div className="topbar"><div className="top-left"><span style={{fontSize:22}}>☰</span><span className="project-name">Lemon Office</span><span className="status">Activ</span><span className="top-muted">Actualizat: 02.07.2026 16:45</span></div><div className="top-right"><span>☀️ 33°C</span><span className="notif">🔔</span><div className="avatar">PM</div><b>Project Manager</b></div></div>}
function Dashboard(){return <><div className="kpis"><Kpi title="Progres general" val="74%" small="în creștere ↑ 8%" color="green" w="74%"/><Kpi title="Demolări" val="93%" small="în creștere ↑ 15%" color="green" w="93%"/><Kpi title="Evacuare deșeuri" val="70%" small="în desfășurare ↑ 20%" color="orange" w="70%"/><Kpi title="Cost total estimat" val="1.248.560" small="RON din 1.690.000 RON" color="blue" w="74%"/><Kpi title="Zile rămase" val="54" small="Data finală: 25.08.2026" color="blue" w="45%"/><Kpi title="Riscuri active" val="3" small="1 critic, 2 medii" color="red" w="60%"/></div><div className="dashboard"><div><div className="left"><Zones/><Critical/><Gantt/><PhotoStation/><Risks/><Costs/><Tasks/><Ai/></div></div><div><Calendar/><Timeline/></div></div></>}
function Kpi(p){return <div className="card"><div className="kpi-head">{p.title}</div><div className={'kpi-val '+(p.color+'Text')}>{p.val}</div><div className="barbg"><span className={'bar '+p.color} style={{width:p.w}}></span></div><div className="muted">{p.small}</div></div>}
function Zones(){const rows=[['P01','Open Space','92%','green'],['P02','Open Space','95%','green'],['P05','P05 (viitor)','0%','orange'],['P08','Meeting Room','0%','blue'],['P10','Camera IT','100%','green'],['P11','Camera Electrică','100%','green'],['P12','Grup Sanitar','0%','blue']];return <div className="card"><div className="panel-title">Progres pe zone</div>{rows.map(r=><div className="zone-row" key={r[0]}><b>{r[0]}</b><span>{r[1]}</span><div className="barbg" style={{margin:0}}><span className={'bar '+r[3]} style={{width:r[2]}}></span></div><span>{r[2]}</span></div>)}</div>}
function Critical(){const rows=[['Evacuare deșeuri rămase','P01, P02','High','red'],['Sortare și etichetare cabluri','P01, P02, P11','High','red'],['Curățare front de lucru','P01, P02','Medium','orange'],['Verificare instalații HVAC','Toate zonele','High','orange'],['Trasare pereți noi','P05 și rest','Medium','orange']];return <div className="card"><div className="panel-title">Activități critice</div>{rows.map(r=><div className="task-row" key={r[0]}><span className={'round '+r[3]}>!</span><div><b>{r[0]}</b><div className="muted">{r[1]}</div></div><span className={'badge '+(r[2]=='High'?'high':'med')}>{r[2]}</span></div>)}</div>}
function Calendar(){const days=['L','M','M','J','V','S','D'],nums=['30','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31'];return <div className="card calendar-card"><div className="cal-top"><h3>Iulie 2026</h3><span>‹ ›</span></div><div className="calendar">{days.map(d=><div className="calh" key={d}>{d}</div>)}{nums.map(n=><div className={n=='2'?'day active':'day'} key={n}>{n}{['3','16','25','26'].includes(n)&&<div className="dot"/>}</div>)}</div></div>}
function Timeline(){const items=[['16:45','Poze încărcate','Ph05 - P01, P02, P05 · 18 imagini','green'],['16:40','AI Vision analiză finalizată','Progres actualizat automat · scor 96%','green'],['16:30','Site Diary actualizat','Raport zilnic adăugat','blue'],['16:10','Task nou creat','Sortare cabluri și etichetare','orange'],['15:55','Materiale actualizate','5 materiale planificate','purple']];return <div className="card" style={{marginTop:14}}><div className="panel-title">Timeline astăzi</div><div className="timeline">{items.map(i=><div className={'timeline-item '+i[3]} key={i[0]}><div className="time">{i[0]}</div><b>{i[1]}</b><div className="muted">{i[2]}</div></div>)}</div></div>}
function Gantt(){const rows=[['Demolări','8','93','green'],['Colectare deșeuri','22','70','orange'],['Evacuare deșeuri','38','70','orange'],['Verificare electrică','48','30','orange'],['Trasare pereți','55','0','gray']];return <div className="card wide"><div className="panel-title">Gantt - sumar</div><div className="gantt"><div className="g-head"><div>Activitate</div><div>Jun 30 - Jul 13</div></div>{rows.map(r=><div className="g-row" key={r[0]}><div>{r[0]}</div><div className="g-area"><div className="today"></div><div className={'gbar '+r[3]} style={{left:r[1]+'%',width:Math.max(12,Number(r[2])*.45)+'%'}}></div></div></div>)}</div><div className="legend"><span>■ Finalizat</span><span>■ În desfășurare</span><span>— Astăzi</span></div></div>}
function PhotoStation(){const arr=['Ph01 - Open Space','Ph02 - P10 IT','Ph05 - P05 viitor','Ph03 - P12 Grup sanitar','Ph04 - P08 Meeting','Ph09 - Electric'];return <div className="card wide"><div className="panel-title">Photo Station - Astăzi</div><div className="photos">{arr.map((a,i)=><div className="photo" key={a}><div className="ph-img" style={{background:`linear-gradient(135deg,#${['1e293b','334155','475569','64748b','0f172a','334155'][i]},#94a3b8)`}}></div><div className="photo-info"><b>{a}</b><br/><span className="muted">02.07.2026 16:{40+i}</span></div></div>)}</div></div>}
function Risks(){return <div className="card"><div className="panel-title">Riscuri principale</div>{['Evacuarea întârzie începerea noilor compartimentări','Instalațiile trebuie verificate înainte de închidere','Goluri în pardoseala tehnică - risc accident'].map((r,i)=><div className="risk-row" key={r}><span className="round red">!</span><span>{r}</span><span className={i==0?'badge high':'badge med'}>{i==0?'Critic':'Mediu'}</span></div>)}</div>}
function Costs(){return <div className="card"><div className="panel-title">Costuri pe categorii</div><div className="donut"><div className="donut-inner">248.350<br/>RON</div></div><p className="muted">Materiale 57% · Manoperă 29% · Utilaje 7%</p></div>}
function Tasks(){return <div className="card"><div className="panel-title">Task-uri</div><div className="donut" style={{background:'conic-gradient(#22c55e 0 42%,#f97316 42% 90%,#cbd5e1 90%)'}}><div className="donut-inner">67<br/>total</div></div></div>}
function Ai(){return <div className="card"><div className="panel-title">AI Vision Summary</div><div className="ai-score">96%</div><p className="muted">Scor progres · îmbunătățire +12%</p></div>}
