'use client';
import Image from 'next/image';
import {useMemo,useState} from 'react';

type Status='Planning'|'In Progress'|'Blocked'|'Done'; type TS='Todo'|'In Progress'|'Blocked'|'Done';
type Zone={id:string;code:string;name:string;area:number}; type Project={id:string;name:string;code:string;beneficiary:string;contractor:string;startDate:string;endDate:string;status:Status;zones:Zone[]};
type Task={id:string;projectId:string;phase:string;title:string;zone:string;owner:string;start:string;end:string;status:TS;progress:number;depends:string};
type Event={id:string;projectId:string;title:string;date:string;time:string;type:string}; type Material={id:string;projectId:string;name:string;zone:string;qty:number;ordered:number;price:number;waste:number;source:string;location:string}; type Photo={id:string;projectId:string;ph:string;url:string;file:string}; type Plan={id:string;projectId:string;title:string;file:string;url:string};

const zones=[['P01','Foyer',7.71],['P02','Showroom',21.93],['P03','Depozitare aparate',5.62],['P04','Birou Open Space',40.81],['P05','Meeting Room',11.74],['P06','Depozitare aparate',5.78],['P07','Chicinetă',5.01],['P08','Meeting Room',5.76],['P09','G.S.01',3.71],['P10','Camera IT',4.8],['P11','Depozitare',4.65],['P12','G.S.02',3.7]].map((z,i)=>({id:'z'+i,code:z[0] as string,name:z[1] as string,area:z[2] as number}));
const nav=['Portfolio','Dashboard','Planuri','Site Diary','Calendar','Tasks','Gantt','Photo Stations','AI Vision','Material Tracker','Elemente tehnice','Reports','Share View','Settings'];
const phs=[['ph01','Ph01','Intrare / spațiu deschis existent','P01,P02,P03,P05,P06'],['ph05','Ph05','Volum central / open space + chicinetă','P04,P07'],['ph06','Ph06','Grupuri sanitare existente','P09,P12'],['ph07','Ph07','Meeting Room existent','P08'],['ph08','Ph08','Spațiu tehnic','P10'],['ph09','Ph09','Depozitare / tablou electric','P11']];

function sum(z:Zone[]){return Number(z.reduce((a,x)=>a+x.area,0).toFixed(2))}
function ind(t:Task){const today=new Date();const end=new Date(t.end+'T00:00:00');if(t.status==='Done')return{l:'Închis',c:'green'};if(t.status==='Blocked'||today>end)return{l:t.status==='Blocked'?'Blocat':'Întârziere',c:'red'};return{l:t.progress<40?'Risc':'În grafic',c:t.progress<40?'red':'green'}}
function matCost(m:Material){const q=m.qty*(1+m.waste/100);return q*m.price}
function areaWall(){return {area:36,boards:24,cw:21,uw:8,screws:648,compound:17}}

export default function Home(){
 const[active,setActive]=useState('Dashboard'),[light,setLight]=useState(false);
 const[projects,setProjects]=useState<Project[]>([{id:'lemon',name:'Lemon – One Cotroceni',code:'LEM-OC-001',beneficiary:'Lemon',contractor:'ADERUS Construct',startDate:'2026-06-30',endDate:'2026-07-24',status:'In Progress',zones}]);
 const[projectId,setProjectId]=useState('lemon'); const project=useMemo(()=>projects.find(p=>p.id===projectId)||projects[0],[projects,projectId]);
 const[tasks,setTasks]=useState<Task[]>([{id:'T001',projectId:'lemon',phase:'Demolări',title:'Finalizare demolări pereți',zone:'P01,P02,P03,P05,P06',owner:'ADERUS',start:'2026-06-30',end:'2026-07-02',status:'In Progress',progress:85,depends:''},{id:'T002',projectId:'lemon',phase:'Evacuare',title:'Evacuare moloz și profile',zone:'P01,P02,P03,P04,P05,P06',owner:'ADERUS',start:'2026-07-02',end:'2026-07-03',status:'Todo',progress:20,depends:'T001'},{id:'T003',projectId:'lemon',phase:'Trasare',title:'Trasare pereți noi',zone:'P02,P03,P04,P05,P06,P07',owner:'ADERUS',start:'2026-07-03',end:'2026-07-04',status:'Todo',progress:0,depends:'T002'},{id:'T004',projectId:'lemon',phase:'Instalații',title:'Verificare tablou electric',zone:'P11',owner:'Electric',start:'2026-07-02',end:'2026-07-02',status:'Todo',progress:0,depends:''}]);
 const[events,setEvents]=useState<Event[]>([{id:'E001',projectId:'lemon',title:'Evacuare deșeuri',date:'2026-07-02',time:'08:30',type:'Task'},{id:'E002',projectId:'lemon',title:'Verificare tablou electric',date:'2026-07-02',time:'11:00',type:'Reminder'}]);
 const[materials,setMaterials]=useState<Material[]>([{id:'M001',projectId:'lemon',name:'Placă gips-carton standard 12.5 mm',zone:'P02',qty:120,ordered:0,price:24,waste:10,source:'https://www.dedeman.ro/ro/search?text=placa%20gips%20carton%2012.5',location:'OCP_E0_A_Plan compartimentare | P02/P03/P05/P06 | interaxe conform plan'},{id:'M002',projectId:'lemon',name:'Profil metalic CW/UW 75',zone:'P02',qty:65,ordered:0,price:22,waste:5,source:'https://www.dedeman.ro/ro/search?text=profil%20CW%2075',location:'OCP_E0_A_Plan trasare | trasee pereți noi | P02-P06'}]);
 const[photos,setPhotos]=useState<Photo[]>([]),[plans,setPlans]=useState<Plan[]>([]),[ph,setPh]=useState('ph01'),[day,setDay]=useState('2026-07-02'),[eventTitle,setEventTitle]=useState(''),[ai,setAi]=useState<any[]>([]);
 const pt=tasks.filter(t=>t.projectId===project.id), pe=events.filter(e=>e.projectId===project.id), pm=materials.filter(m=>m.projectId===project.id), risk=pt.filter(t=>ind(t).c==='red').length, cost=pm.reduce((a,m)=>a+matCost(m),0);
 function updTask(id:string,f:keyof Task,v:any){setTasks(tasks.map(t=>t.id===id?{...t,[f]:v,...(f==='status'&&v==='Done'?{progress:100}:{})}:t))}
 function addTask(){setTasks([...tasks,{id:`T${String(tasks.length+1).padStart(3,'0')}`,projectId:project.id,phase:'Nou',title:'Task nou',zone:'',owner:'',start:'2026-07-02',end:'2026-07-02',status:'Todo',progress:0,depends:''}])}
 function addProject(){const id='project-'+(projects.length+1);setProjects([...projects,{id,name:'Proiect nou',code:`PRJ-${String(projects.length+1).padStart(3,'0')}`,beneficiary:'',contractor:'',startDate:'2026-07-01',endDate:'2026-07-31',status:'Planning',zones:[]}]);setProjectId(id);setActive('Settings')}
 function uploadPlans(f:FileList|null){if(!f)return;setPlans([...plans,...Array.from(f).map((x,i)=>({id:'PL'+Date.now()+i,projectId:project.id,title:x.name.replace(/\.[^/.]+$/,''),file:x.name,url:URL.createObjectURL(x)}))])}
 function uploadPhotos(f:FileList|null){if(!f)return;setPhotos([...photos,...Array.from(f).map((x,i)=>({id:'PHO'+Date.now()+i,projectId:project.id,ph,url:URL.createObjectURL(x),file:x.name}))])}
 function runAi(){setAi([{id:'AI'+Date.now(),elements:['moloz / deșeuri în front','compartimentări demolate','instalații aparente'],materials:['profile CW/UW','plăci GK','bandă + masă rosturi'],risks:['evacuarea deșeurilor este critică pentru următorul front','verifică instalațiile înainte de închiderea pereților'],confidence:64},...ai])}
 return <div className={light?'app light':'app'}><header className="head"><div className="brand"><Image src="/omifa-logo.png" width={88} height={40} alt="Omifa" className="logo"/><div><div className="title">PM Omifa v2.0 Preview</div><div className="sub">{project.name}</div></div></div><button className="btn btn2" onClick={()=>setLight(!light)}>{light?'Night mode':'Light mode'}</button></header><div className="layout"><aside className="side"><div className="nav">{nav.map(n=><button key={n} className={active===n?'active':''} onClick={()=>setActive(n)}>{n}</button>)}</div></aside><main className="main">
 {active==='Portfolio'&&<Portfolio projects={projects} tasks={tasks} setProjectId={setProjectId} addProject={addProject}/>}
 {active==='Dashboard'&&<Dashboard project={project} tasks={pt} events={pe} risk={risk} cost={cost} materials={pm}/>}
 {active==='Planuri'&&<Plans plans={plans.filter(p=>p.projectId===project.id)} upload={uploadPlans}/>}
 {active==='Site Diary'&&<Diary/>}
 {active==='Calendar'&&<Calendar events={pe} day={day} setDay={setDay} eventTitle={eventTitle} setEventTitle={setEventTitle} setEvents={setEvents} eventsAll={events} projectId={project.id}/>}
 {active==='Tasks'&&<Tasks tasks={pt} upd={updTask} add={addTask}/>}
 {active==='Gantt'&&<Gantt tasks={pt}/>}
 {active==='Photo Stations'&&<Photos ph={ph} setPh={setPh} photos={photos.filter(p=>p.projectId===project.id)} upload={uploadPhotos}/>}
 {active==='AI Vision'&&<Ai runAi={runAi} results={ai}/>}
 {active==='Material Tracker'&&<Materials materials={pm} all={materials} setMaterials={setMaterials}/>}
 {active==='Elemente tehnice'&&<Technical/>}
 {active==='Reports'&&<Report project={project} tasks={pt} cost={cost}/>}
 {active==='Share View'&&<Share project={project} tasks={pt}/>}
 {active==='Settings'&&<Settings project={project} setProjects={setProjects} projects={projects}/>}
 </main></div></div>
}
function KPI({t,v}:{t:string;v:any}){return <div className="card"><div className="muted">{t}</div><div className="stat">{v}</div></div>}
function Dashboard({project,tasks,events,risk,cost,materials}:any){return <div className="dash"><div><div className="grid"><KPI t="Suprafață" v={`${sum(project.zones).toFixed(2)} mp`}/><KPI t="Riscuri" v={risk}/><KPI t="Cost estimat" v={`${Math.round(cost).toLocaleString('ro-RO')} lei`}/><KPI t="Materiale de comandat" v={materials.filter((m:any)=>m.ordered===0).length}/></div><div className="card"><h2>Construction Intelligence</h2><div className="notice">{risk?'Evacuarea deșeurilor este critică pentru deblocarea următoarei faze.':'Proiectul este în grafic.'}</div></div><div className="card"><h2>Timeline azi</h2><div className="timeline"><div className="tl"><b>08:30</b><br/><span className="muted">Evacuare deșeuri / moloz.</span></div><div className="tl"><b>11:00</b><br/><span className="muted">Verificare P11 tablou electric.</span></div><div className="tl"><b>17:00</b><br/><span className="muted">Update Photo Stations + raport zilnic.</span></div></div></div><TaskTable tasks={tasks}/></div><CalendarMini events={events}/></div>}
function CalendarMini({events}:any){return <div className="card"><h2>Calendar</h2><div className="calendar">{Array.from({length:31},(_,i)=>`2026-07-${String(i+1).padStart(2,'0')}`).map(d=><div className="day" key={d}><b>{Number(d.slice(-2))}</b>{events.filter((e:any)=>e.date===d).map((e:any)=><div className="dayitem" key={e.id}>{e.title}</div>)}</div>)}</div></div>}
function TaskTable({tasks}:any){return <div className="card"><h2>Task-uri</h2><table><thead><tr><th>ID</th><th>Fază</th><th>Task</th><th>Zone</th><th>Status</th><th>%</th><th>Indicator</th></tr></thead><tbody>{tasks.map((t:Task)=>{const i=ind(t);return <tr key={t.id}><td>{t.id}</td><td>{t.phase}</td><td>{t.title}</td><td>{t.zone}</td><td>{t.status}</td><td>{t.progress}%</td><td><span className={'pill '+i.c}>{i.l}</span></td></tr>})}</tbody></table></div>}
function Portfolio({projects,tasks,setProjectId,addProject}:any){return <div className="card"><div className="row" style={{justifyContent:'space-between'}}><h2>Portofoliu</h2><button className="btn" onClick={addProject}>+ Proiect nou</button></div><table><tbody>{projects.map((p:Project)=><tr key={p.id}><td>{p.code}</td><td>{p.name}</td><td>{sum(p.zones).toFixed(2)} mp</td><td>{tasks.filter((t:Task)=>t.projectId===p.id&&ind(t).c==='red').length} riscuri</td><td><button className="btn btn2" onClick={()=>setProjectId(p.id)}>Deschide</button></td></tr>)}</tbody></table></div>}
function Plans({plans,upload}:any){const[sel,setSel]=useState('');const cur=plans.find((p:any)=>p.id===sel)||plans[0];return <div className="card"><div className="row" style={{justifyContent:'space-between'}}><h2>Plan Viewer</h2><input type="file" multiple accept="application/pdf,image/*" onChange={e=>upload(e.target.files)}/></div><div className="plan"><div>{plans.length===0&&<div className="notice">Încarcă PDF sau imagine cu planul.</div>}{plans.map((p:any)=><div className="card" key={p.id} onClick={()=>setSel(p.id)}><b>{p.title}</b><br/><span className="muted">{p.file}</span></div>)}</div><div className="prev">{cur?.url?(cur.file.toLowerCase().endsWith('.pdf')?<iframe src={cur.url}/>:<img src={cur.url} alt={cur.title}/>):<span className="muted">Selectează un plan.</span>}</div></div></div>}
function Diary(){return <div className="card"><h2>Site Diary</h2><div className="card"><b>01.07.2026</b> <span className="pill amber">Stand-by</span><p>Nu s-au executat lucrări. Echipa nu a intervenit pe șantier.</p><ul><li>Evacuare deșeuri dimineață</li><li>Curățare fronturi</li><li>Verificare tablou electric P11</li></ul></div></div>}
function Calendar(p:any){function add(){if(!p.eventTitle)return;p.setEvents([...p.eventsAll,{id:'E'+Date.now(),projectId:p.projectId,title:p.eventTitle,date:p.day,time:'09:00',type:'Reminder'}]);p.setEventTitle('')}return <div className="dash"><CalendarMini events={p.events}/><div className="card"><h2>Zi selectată</h2><input type="date" value={p.day} onChange={e=>p.setDay(e.target.value)}/>{p.events.filter((e:any)=>e.date===p.day).map((e:any)=><div className="notice" key={e.id}>{e.time} – {e.title}</div>)}<label>Eveniment nou</label><input value={p.eventTitle} onChange={e=>p.setEventTitle(e.target.value)}/><button className="btn" onClick={add}>Adaugă</button></div></div>}
function Tasks({tasks,upd,add}:any){return <div className="card"><button className="btn" onClick={add}>+ Task</button><table><tbody>{tasks.map((t:Task)=><tr key={t.id}><td>{t.id}</td><td><input value={t.phase} onChange={e=>upd(t.id,'phase',e.target.value)}/></td><td><input value={t.title} onChange={e=>upd(t.id,'title',e.target.value)}/></td><td><select value={t.status} onChange={e=>upd(t.id,'status',e.target.value)}><option>Todo</option><option>In Progress</option><option>Blocked</option><option>Done</option></select></td><td><input type="number" value={t.progress} onChange={e=>upd(t.id,'progress',Number(e.target.value))}/></td><td><input value={t.depends} onChange={e=>upd(t.id,'depends',e.target.value)}/></td></tr>)}</tbody></table></div>}
function Gantt({tasks}:any){const dated=tasks.filter((t:Task)=>t.start&&t.end);const ms=dated.flatMap((t:Task)=>[new Date(t.start+'T00:00:00').getTime(),new Date(t.end+'T00:00:00').getTime()]);const min=ms.length?Math.min(...ms):Date.now();const max=ms.length?Math.max(...ms):Date.now()+86400000;const total=Math.max(1,Math.round((max-min)/86400000)+1);const days=Array.from({length:total},(_,i)=>new Date(min+i*86400000));const now=new Date();const today=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime();const left=Math.max(0,Math.min(100,((today-min)/(total*86400000))*100));return <div className="card"><button className="btn no-print" onClick={()=>window.print()}>Print A2</button><h2>Gantt profesional</h2><div className="gantt"><div className="scale"><div className="meta">Activitate</div><div className="days">{days.map((d,i)=><div className="gday" key={i}><b>{d.getDate()}</b><br/>{d.toLocaleString('ro-RO',{month:'short'})}</div>)}</div></div><div style={{position:'relative'}}><div className="today" style={{left:`calc(250px + ${left}% * (100% - 250px) / 100)`}}><span>Azi</span></div>{dated.map((t:Task)=>{const i=ind(t);const s=new Date(t.start+'T00:00:00').getTime(),e=new Date(t.end+'T00:00:00').getTime();const l=Math.max(0,((s-min)/(total*86400000))*100),w=Math.max(3,(((e-s)/86400000+1)/total)*100);return <div className="lane" key={t.id}><div className="meta"><span className={'pill '+i.c}>{t.id}</span><span>{t.phase}</span></div><div className="area"><div className={'bar '+(i.c==='red'?'bad':'')} style={{left:`${l}%`,width:`${w}%`}}>{(`${t.id} · ${t.title}`).slice(0,36)}</div></div></div>})}</div></div></div>}
function Photos({ph,setPh,photos,upload}:any){return <div className="dash"><div className="card"><h2>Photo Stations</h2>{phs.map(s=><div className="card" key={s[0]} onClick={()=>setPh(s[0])}><b>{s[1]}</b><br/><span className="muted">{s[2]} · {s[3]}</span></div>)}</div><div className="card"><input type="file" multiple accept="image/*" onChange={e=>upload(e.target.files)}/><div className="gallery">{photos.filter((p:Photo)=>p.ph===ph).map((p:Photo)=><div key={p.id}><img src={p.url} alt={p.file}/><span className="muted">{p.file}</span></div>)}</div></div></div>}
function Ai({runAi,results}:any){return <div className="dash"><div className="card"><h2>AI Vision</h2><p className="muted">Activ local/demo. Pregătit pentru API real.</p><button className="btn" onClick={runAi}>Rulează AI Ready</button><div className="ai">Poze → analiză → elemente detectate → materiale sugerate → riscuri → raport</div></div><div className="card">{results.map((r:any)=><div className="card" key={r.id}><b>Local demo</b> <span className="pill">{r.confidence}%</span><ul>{r.elements.map((x:string)=><li key={x}>{x}</li>)}</ul><h3>Materiale</h3><ul>{r.materials.map((x:string)=><li key={x}>{x}</li>)}</ul></div>)}</div></div>}
function Materials({materials,setMaterials}:any){function upd(id:string,f:keyof Material,v:any){setMaterials((all:Material[])=>all.map(m=>m.id===id?{...m,[f]:v}:m))}return <div className="card"><h2>Material Tracker</h2><table><tbody>{materials.map((m:Material)=><tr key={m.id}><td><input value={m.name} onChange={e=>upd(m.id,'name',e.target.value)}/><span className="muted">{m.location}</span></td><td><input type="number" value={m.qty||''} onChange={e=>upd(m.id,'qty',Number(e.target.value))}/></td><td><input type="number" value={m.ordered||''} onChange={e=>upd(m.id,'ordered',Number(e.target.value))}/></td><td>{Math.max(0,m.qty*(1+m.waste/100)-m.ordered).toFixed(2)}</td><td><input type="number" value={m.price||''} onChange={e=>upd(m.id,'price',Number(e.target.value))}/></td><td>{Math.round(matCost(m)).toLocaleString('ro-RO')}</td><td><a href={m.source} target="_blank">referință</a></td></tr>)}</tbody></table></div>}
function Technical(){const q=areaWall();return <div className="dash"><div className="card"><h2>Elemente tehnice</h2><table><tbody><tr><td>Suprafață perete</td><td>{q.area} mp</td></tr><tr><td>Plăci estimate</td><td>{q.boards} buc</td></tr><tr><td>Profile CW</td><td>{q.cw}</td></tr><tr><td>Profile UW</td><td>{q.uw}</td></tr></tbody></table></div><div className="card"><h2>Documentații</h2>{[['Knauf','https://www.knauf.ro/ro/documentatie'],['Rigips','https://www.rigips.ro/documentatii'],['Siniat','https://www.siniat.ro/ro-ro/centru-de-documentatie']].map(d=><div className="notice" key={d[0]}><b>{d[0]}</b><br/><a href={d[1]} target="_blank">Deschide documentație</a></div>)}<div className="ai">AI Ready: compară poze cu elemente tehnice și propune cantități.</div></div></div>}
function Report({project,tasks,cost}:any){return <div className="card"><button className="btn no-print" onClick={()=>window.print()}>Print raport</button><h2>Raport – {project.name}</h2><TaskTable tasks={tasks}/><h2>Cost estimat</h2><p>{Math.round(cost).toLocaleString('ro-RO')} lei</p></div>}
function Share({project,tasks}:any){return <div className="card"><h2>Share View</h2><input readOnly value={`https://pm-omifa.vercel.app/share/${project.id}`}/><TaskTable tasks={tasks}/></div>}
function Settings({project,setProjects,projects}:any){function setZone(code:string,area:number){const zones=project.zones.map((z:Zone)=>z.code===code?{...z,area}:z);setProjects(projects.map((p:Project)=>p.id===project.id?{...project,zones}:p))}return <div className="dash"><div className="card"><h2>Setări</h2><label>Nume</label><input value={project.name} readOnly/><label>Suprafață calculată</label><input readOnly value={`${sum(project.zones).toFixed(2)} mp`}/></div><div className="card"><h2>Zone</h2><table><tbody>{project.zones.map((z:Zone)=><tr key={z.code}><td>{z.code}</td><td>{z.name}</td><td><input type="number" value={z.area} onChange={e=>setZone(z.code,Number(e.target.value))}/></td></tr>)}</tbody></table></div></div>}
